/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyCart {
    }
}
declare global {
    interface HTMLMyCartElement extends Components.MyCart, HTMLStencilElement {
    }
    var HTMLMyCartElement: {
        prototype: HTMLMyCartElement;
        new (): HTMLMyCartElement;
    };
    interface HTMLElementTagNameMap {
        "my-cart": HTMLMyCartElement;
    }
}
declare namespace LocalJSX {
    interface MyCart {
    }
    interface IntrinsicElements {
        "my-cart": MyCart;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-cart": LocalJSX.MyCart & JSXBase.HTMLAttributes<HTMLMyCartElement>;
        }
    }
}
